-- Initial schema: tenancy spine + first domain slice.
-- See docs/domain-model.md and ADR-0004 (shared schema, gym_id on every tenant table).
--
-- IDs are UUIDv7, generated by the application (and, later, on-device for offline
-- creation — ADR-0008). We do not use gen_random_uuid() so clients can create rows
-- offline with globally-unique, time-ordered ids.

-- ------------------------------------------------------------------ gyms

CREATE TABLE gyms (
    id          UUID PRIMARY KEY,
    name        TEXT        NOT NULL CHECK (length(btrim(name)) BETWEEN 1 AND 120),
    slug        TEXT        NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9][a-z0-9-]{1,62}$'),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ----------------------------------------------------------------- users

-- Users are platform-global (one person can belong to several gyms), so this
-- table intentionally has no gym_id. Tenancy is expressed via `memberships`.
CREATE TABLE users (
    id             UUID PRIMARY KEY,
    email          TEXT        NOT NULL UNIQUE CHECK (email = lower(email)),
    display_name   TEXT        NOT NULL CHECK (length(btrim(display_name)) BETWEEN 1 AND 50),
    password_hash  TEXT        NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ----------------------------------------------------------- memberships

-- Links a user to a gym with a role. This is what makes someone a member at
-- Gym A and an instructor at Gym B simultaneously (docs/authorization-model.md).
CREATE TABLE memberships (
    id          UUID PRIMARY KEY,
    gym_id      UUID        NOT NULL REFERENCES gyms(id) ON DELETE CASCADE,
    user_id     UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role        TEXT        NOT NULL CHECK (role IN ('owner','admin','head_coach','instructor','member')),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    revoked_at  TIMESTAMPTZ
);

-- A user holds at most one *active* role per gym.
CREATE UNIQUE INDEX memberships_active_unique
    ON memberships (gym_id, user_id)
    WHERE revoked_at IS NULL;

CREATE INDEX memberships_user_idx ON memberships (user_id) WHERE revoked_at IS NULL;
CREATE INDEX memberships_gym_idx  ON memberships (gym_id)  WHERE revoked_at IS NULL;

-- ------------------------------------------------------------- exercises

CREATE TABLE exercises (
    id          UUID        PRIMARY KEY,
    gym_id      UUID        NOT NULL REFERENCES gyms(id) ON DELETE CASCADE,
    name        TEXT        NOT NULL CHECK (length(btrim(name)) BETWEEN 1 AND 120),
    modality    TEXT        NOT NULL CHECK (modality IN ('repetitions','duration','distance')),
    notes       TEXT        CHECK (notes IS NULL OR length(notes) <= 1000),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX exercises_gym_idx ON exercises (gym_id);

-- Exercise names are unique per gym (case-insensitively), not globally.
CREATE UNIQUE INDEX exercises_gym_name_unique ON exercises (gym_id, lower(name));

-- -------------------------------------------------------------- sessions

-- Refresh-token sessions. We store only a HASH of the token; the raw token is
-- returned to the client once and never persisted server-side.
-- Rotation + reuse detection: `rotated_from` chains a token family so that
-- presenting an already-rotated token lets us revoke the whole family.
CREATE TABLE sessions (
    id            UUID        PRIMARY KEY,
    user_id       UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash    BYTEA       NOT NULL UNIQUE,
    device_label  TEXT        CHECK (device_label IS NULL OR length(device_label) <= 100),
    expires_at    TIMESTAMPTZ NOT NULL,
    rotated_from  UUID        REFERENCES sessions(id) ON DELETE SET NULL,
    revoked_at    TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX sessions_user_idx ON sessions (user_id) WHERE revoked_at IS NULL;
CREATE INDEX sessions_expiry_idx ON sessions (expires_at) WHERE revoked_at IS NULL;
